config/routes.rb
Rexaminator::Application.routes.draw do

  resources :categories
  resources :questions
  resources :categories
  resources :feedbacks

  resources :exam_questions do
    member do
      put :reset
      get :review
    end
  end

  resources :exams do
    member do
      get :start
      get :go
      get :finish
      get :export
    end
  end

  resources :sessions

  match 'admin',  :to => 'exams#index'
  match 'login',  :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

   root :to => 'exams#new'

  match '/:controller(/:action(/:id))(.:format)'

end

app/models/feedback.rb
class Feedback < ActiveRecord::Base

  CATEGORIES = {
                :bug        => 'I have found a bug in this question',
                :other      => 'I just want to comment this question'
               }

  belongs_to :question

  validates_presence_of :question_id
  validates_presence_of :category
  validates_presence_of :body
  validates_presence_of :author

  attr_accessible :question_id, :category, :body, :author

  def self.category_options
    CATEGORIES.invert.sort
  end

end

app/controllers/feedbacks_controller.rb
class FeedbacksController < ApplicationController

  before_filter :session_expiry
  before_filter :authorize, :except => [:create]

  def index
    @feedbacks = Feedback.order('created_at DESC')
  end

  def create
    @feedback = Feedback.new(params[:feedback])
    respond_to do |format|
      if @feedback.save
        flash[:notice] = "Your feedback has been successfully sent. Thank You."
        format.html {redirect_to review_exam_question_path(:id => params[:exam_question_id], :order_number => params[:order_number])}
        format.js
      else
        format.html do
          redirect_to review_exam_question_path(:id => params[:exam_question_id], :order_number => params[:order_number])
        end
        format.js {render :action => :error}
      end
    end

  end

  def edit
    @feedback = Feedback.find(params[:id])
  end

  def update
    @feedback = Feedback.find(params[:id])
    respond_to do |format|
      if @feedback.update_attributes(params[:feedback])
        flash[:notice] = 'Feedback was successfully updated.'
        format.html { redirect_to feedbacks_url }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  def show
    @feedback = Feedback.find(params[:id])
    respond_to do |format|
      format.html
    end
  end

  def destroy
    @feedback = Feedback.find(params[:id])
    @feedback.destroy

    respond_to do |format|
      format.html { redirect_to(feedbacks_url) }
    end
  end

end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/create.js.erb
$('#newexamloader').hide();
$('#errorExplanation').remove();
$('p.notice').remove();
$('#feedback').hide();
$('#feedback').before("<p class='notice'><%= escape_javascript flash.delete(:notice) %></p>");

app/views/feedbacks/edit.html.erb
<h2>Editing feedback id: <%= @feedback.id %></h2>

<%= form_for @feedback do |f| %>
  <%= f.error_messages %>

  <h3>Active</h3>
  <p> <%= f.check_box :active %> </p>

  <h3>Category:</h3>
  <div class="rbox">
    <p><%= @feedback.category %></p>
  </div>

  <h3>Body:</h3>
  <div class="rbox">
    <p><pre><%= @feedback.body %></pre></p>
  </div>

  <h3>Author:</h3>
  <div class="rbox">
    <p><%= @feedback.author %></p>
  </div>

  <h3>Created:</h3>
  <div class="rbox">
    <p><%= @feedback.created_at %></p>
  </div>

  <h3>Question ID:</h3>
  <div class="rbox">
    <p><%=link_to @feedback.question_id, question_path(@feedback.question) %></p>
  </div>

  <p>
    <%= f.submit "Update" %>
  </p>
<% end %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/error.js.erb
$('#newexamloader').hide();
$('#errorExplanation').remove();
$('p.notice').remove();
$('#new_feedback').before("<div id='errorExplanation'> \
                             <h2>Invalid feedback data. Please correct and try again</h2> \
                             <ul> \
                                <% @feedback.errors.full_messages.each do |msg| %> \
                               <li><%= msg %></li> \
                               <% end %> \
                             </ul> \
                           </div> \
                          ");

app/views/feedbacks/index.html.erb
<h1>Feedbacks</h1>
<table class="listing">
  <tr>
    <th>Id</th>
    <th>Active</th>
    <th>Category</th>
    <th>Body</th>
    <th>Author</th>
    <th>Created</th>
    <th>Question</th>
    <th></th>
  </tr>
<% for feedback in @feedbacks -%>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= feedback.id  %></td>
    <td><%= feedback.active %></td>
    <td><%= feedback.category %></td>
    <td><%= truncate(feedback.body, :length => 120) %></td>
    <td><%= feedback.author %></td>
    <td><%= feedback.created_at.to_date %> </td>
    <td><%=link_to feedback.question_id, question_path(feedback.question) %></td>
    <td>
      <div><%= link_to 'Show', feedback %></div>
      <div><%= link_to 'Edit', edit_feedback_path(feedback) %></div>
      <div><%= link_to 'Destroy', feedback, :confirm => 'Are you sure?', :method => :delete %></div>
    </td>
  </tr>
<% end -%>
</table>

app/views/feedbacks/show.html.erb
<h2>Feedback id: <%= @feedback.id %></h2>

<h3>Category:</h3>
<div class="rbox">
  <p><%= @feedback.category %></p>
</div>

<h3>Body:</h3>
<div class="rbox">
  <p><pre><%= @feedback.body %></pre></p>
</div>

<h3>Author:</h3>
<div class="rbox">
  <p><%= @feedback.author %></p>
</div>

<h3>Created:</h3>
<div class="rbox">
  <p><%= @feedback.created_at %></p>
</div>

<h3>Question ID:</h3>
<div class="rbox">
  <p><%=link_to @feedback.question_id, question_path(@feedback.question) %></p>
</div>

<%= link_to 'Destroy', @feedback, :confirm => "Are you sure?", :method => :delete %> |
<%= link_to 'Back', feedbacks_path %>