config/routes.rb
Rexaminator::Application.routes.draw do

  resources :categories
  resources :questions
  resources :categories
  resources :feedbacks

  resources :exam_questions do
    member do
      put :reset
      get :review
    end
  end

  resources :exams do
    member do
      get :start
      get :go
      get :finish
      get :export
    end
  end

  resources :sessions

  match 'admin',  :to => 'exams#index'
  match 'login',  :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

   root :to => 'exams#new'

  match '/:controller(/:action(/:id))(.:format)'

end

app/models/category.rb
class Category < ActiveRecord::Base

  has_and_belongs_to_many :questions, :uniq => true

  validates :name, :presence => true, :uniqueness => true

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  before_filter :session_expiry
  before_filter :authorize

  # GET /categories
  def index
    @categories = Category.order(:name)

    respond_to do |format|
      format.html # index.html.erb
    end
  end

  # GET /categories/1
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /categories/new
  def new
    @category = Category.new

    respond_to do |format|
      format.html # new.html.erb
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  def create
    @category = Category.new
    @category.accessible = :all if admin?
    @category.attributes = params[:category]

    respond_to do |format|
      if @category.save
        flash[:notice] = 'Category was successfully created.'
        format.html { redirect_to categories_url }
      else
        format.html { render :action => "new" }
      end
    end
  end

  # PUT /categories/1
  def update
    @category = Category.find(params[:id])
    @category.accessible = :all if admin?

    respond_to do |format|
      if @category.update_attributes(params[:category])
        flash[:notice] = 'Category was successfully updated.'
        format.html { redirect_to categories_url }
      else
        format.html { render :action => "edit" }
      end
    end
  end

  # DELETE /categories/1
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to(categories_url) }
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_form.html.erb
  <% if @category.errors.any? %>
    <div id="errorExplanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>
      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for(@category) do |f| %>

  <h3>Category Name</h3>
  <p> <%= f.text_field :name %> </p>

  <h3>Description</h3>
  <p> <%= f.text_area :description, :cols => 80, :rows => 2, :class => "autogrow" %> </p>

  <p>
    <%= f.submit submit_text %>
  </p>
<% end %>

app/views/categories/edit.html.erb
<h2>Editing category</h2>

<%= render :partial => "form", :locals => {:submit_text => "Update"} %>

<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h2>Categories</h2>

<%= link_to 'New category', new_category_path %>

<table class="listing">
  <tr>
    <th>Id</th>
    <th>Name</th>
    <th>Description</th>
    <th></th>
  </tr>

<% for category in @categories %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= category.id %></td>
    <td><%= category.name %></td>
    <td><%= category.description %></td>
    <td>
      <div><%= link_to 'Show', category %></div>
      <div><%= link_to 'Edit', edit_category_path(category) %></div>
      <div><%= link_to 'Destroy', category, :confirm => 'Are you sure?', :method => :delete %></div>
    </td>
  </tr>
<% end %>
</table>

<br />

app/views/categories/new.html.erb
<h2>New category</h2>

<%= render :partial => "form", :locals => {:submit_text => "Create"} %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h2>Category id: <%= @category.id %></h2>
<h3>Name:</h3>
<p>
  <%= @category.name %>
</p>

<h3>Description:</h3>
<p>
  <%= @category.description %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>