config/routes.rb
Rexaminator::Application.routes.draw do

  resources :categories
  resources :questions
  resources :categories
  resources :feedbacks

  resources :exam_questions do
    member do
      put :reset
      get :review
    end
  end

  resources :exams do
    member do
      get :start
      get :go
      get :finish
      get :export
    end
  end

  resources :sessions

  match 'admin',  :to => 'exams#index'
  match 'login',  :to => 'sessions#new'
  match 'logout', :to => 'sessions#destroy'

   root :to => 'exams#new'

  match '/:controller(/:action(/:id))(.:format)'

end

app/models/exam.rb
class Exam < ActiveRecord::Base

  # minimum and maximum numbers of question for exam
  MIN_NUM_OF_QUESTIONS = 1
  MAX_NUM_OF_QUESTIONS = 30

  include ActiveRecord::Transitions

  has_many :exam_questions, :dependent => :destroy, :order => 'question_id ASC'
  has_many :questions, :through => :exam_questions, :order => 'questions.id ASC'

  validates_presence_of :sessionid
  validate :number_of_questions_should_be_in_valid_range

  scope :generated, where(:state => 'generated')
  scope :started,   where(:state => 'started')
  scope :checked,   where(:state => 'checked')
  scope :completed, where(:state => 'completed')

  state_machine do
    state :generated
    state :started
    state :checked
    state :completed, :enter => [:complete_exam]

    event :start do
      transitions :from => [:generated], :to => :started
    end

    event :check do
      transitions :from => [:started], :to => :checked
    end

    event :complete do
      transitions :from => [:checked], :to => :completed
    end
  end

  def draw_questions(max_num_of_questions)
    self.questions = Question.active.order('Random()').limit(max_num_of_questions)
  end

  def complete_exam
    self.update_attribute(:completed_at, Time.now)
  end

  def number_of_questions_should_be_in_valid_range
    unless self.questions.size.between?(MIN_NUM_OF_QUESTIONS, MAX_NUM_OF_QUESTIONS)
      errors.add(:num_of_questions, "should be greater or equal than #{MIN_NUM_OF_QUESTIONS} and less or equal than #{MAX_NUM_OF_QUESTIONS}")
    end
  end

  def exam_questions_answers(question_id)
    eq = ExamQuestion.where(:exam_id => self.id, :question_id => question_id).first
    return [eq.answer1, eq.answer2, eq.answer3, eq.answer4]
  end

  def check
    self.questions.each do |question|
      eq = ExamQuestion.where(:exam_id => self.id, :question_id =>  question.id).first
      eq.check! if eq.update_attribute(:accurate, question.accurate?(exam_questions_answers(question.id)))
    end
    self.check!
  end

  def accurate
    ExamQuestion.where(:exam_id => self.id, :accurate => true).count
  end

  def score
    all = self.questions.size
    (self.accurate.to_f / all) * 100
  end

  def questions_states
    states = {}
    exam_questions = ExamQuestion.where(:exam_id => self.id).order(:question_id)
    exam_questions.each_with_index do |exam_question, index|
      states[index+1] = exam_question.state
    end
    states
  end

end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  before_filter :authorize, :except => [:new, :create, :start, :go, :finish, :show, :export]
  before_filter :ensure_current_exam, :except => [:index, :new, :create]

  def index
    @num_of_exams = Exam.count
    @exams = Exam.paginate(:page => params[:page], :per_page => 25, :order => 'id DESC')
    @generated_count = Exam.generated.count
    @started_count   = Exam.started.count
    @checked_count   = Exam.checked.count
    @completed_count = Exam.completed.count
  end

  def new
    @exam = Exam.new
    session[:exam] = nil
  end

  def create
    noq_from_params = params[:num_of_questions].to_i
    noq_from_params = 0 if noq_from_params < 0
    max_num_of_questions = [noq_from_params, Exam::MAX_NUM_OF_QUESTIONS].min
    @exam = Exam.new
    @exam.sessionid = session.object_id
    @exam.draw_questions(max_num_of_questions)
    respond_to do |format|
      if @exam.save
        session[:exam] = @exam.id #store exam id in session
        format.html { redirect_to(start_exam_url(@exam))}
      else
        format.html { render :action => "new" }
      end
    end
  end

  def show
    @exam = Exam.find(params[:id])
  end

  def start
    @exam = Exam.find(params[:id])
    @num_of_questions = @exam.questions.size
  end

  def go
    @exam = Exam.includes(:exam_questions => :question).find(params[:id])
    @exam.start! unless @exam.started?
    @exam_questions = @exam.exam_questions
    @questions = @exam_questions.map(&:question).paginate(:page => params[:question], :per_page => 1)
    @question = @questions.first
    @exam_question = @exam_questions.select{|eq| eq.question_id == @question.id}.first
    @exam_question.view!
    @exam_question.save(:validate => false)
    @question_number = params[:question] || "1"
    @num_of_questions = @exam_questions.size
  end

  def finish
    @exam = Exam.includes(:exam_questions => :question).find(params[:id])
    @exam.check unless @exam.checked? or @exam.completed?
    @exam.reload
    @exam_questions = @exam.exam_questions
    @exam_questions_total = @exam_questions.size
    @exam_questions_completed = @exam_questions.select{|eq| ['completed', 'completed_checked'].include?(eq.state)}.size
    @exam_questions_viewed = @exam_questions.select{|eq| ['viewed', 'viewed_checked'].include?(eq.state)}.size + @exam_questions_completed
    @exam_questions_accurate = @exam.accurate
    @exam.complete! unless @exam.completed?
  end

  def destroy
    @exam = Exam.find(params[:id])
    @exam.destroy
    redirect_to(exams_url)
  end

protected

  def ensure_current_exam
    return true if admin?
    unless Exam.find(params[:id]).id == session[:exam]
#      render :file => "#{Rails.root}/public/404.html", :status => 404
      flash[:error] = "Error: Unauthorized access. You have been redirected to home page."
      redirect_to root_url and return false
    end
    true
  end

end

app/helpers/exam_helper.rb
module ExamHelper

  def to_sign(boolean)
    boolean ? '+' : '-'
  end
  
end

app/views/exams/finish.html.erb
<h2 class="center">Your Score: <span id="score"><%= number_to_percentage(@exam.score, :precision => 0) %></span></h2>

<ul id="scoresummary">
  <li title="Total number of questions">total: <%= @exam_questions_total%>,</li>
  <li title="Number of questions visited">viewed: <%= @exam_questions_viewed %>,</li>
  <li title="Number of questions with any answer given">completed: <%= @exam_questions_completed %>,</li>
  <li title="Number of questions with correct answers">correct: <%= @exam_questions_accurate %></li>
</ul>

<ol class="questions_summary">
  <% @exam_questions.each_with_index do |exam_question, index| %>
    <% accurate = exam_question.accurate? %>
    <li title="Click to review question and answers"><%= link_to "Q#{index+1}: <span class=\"#{accurate}\">#{accurate}</span>".html_safe, review_exam_question_path(:id => exam_question.id, :order_number => index+1) %></li>
  <% end %>
</ol>

<div class="center"><%= link_to "&laquo; New Exam &raquo;".html_safe, new_exam_path %></div>

app/views/exams/go.html.erb
<div id="pagination_container">
  <%= will_paginate @questions,
                    :param_name => 'question',
                    :id => 'questions_pagination',
                    :inner_window => @exam_questions.size,
                    :outer_window => @exam_questions.size,
                    :params => {:aasm_links => @exam.questions_states},
                    :renderer => PaginationListLinkRenderer
  %>
</div>
<div id="question">
  <%= will_paginate @questions,
                    :param_name => 'question',
                    :page_links => false
  %>
  <div id="finish_button">
    <%= link_to 'Finish Exam', finish_exam_path(@exam), :confirm => "Finish Exam?", :class => "rbutton", :title => "Finish Exam And Find Your Score" %>
  </div>
  <%= form_for @exam_question, :remote => true do |f| %>
    <h2>Question <%= @question_number %> of <%= @num_of_questions %></h2>
    <div class="rbox question_body">
      <p><%=raw textilize(@question.body) %></p>
    </div>
    <div id="answers" class="rbox">
      <div id="newexamloader"></div>
      <table class="answers_go">
        <% @question.answers.each_with_index do |answer, index| -%>
          <tr>
            <td class="checkbox">
              <%= f.check_box "answer#{index+1}" %>
            </td>
            <td class="answer"><%=raw textilize(answer.body) %></td>
          </tr>
        <% end -%>
      </table>
      <%= f.submit "Save/Update Answer", id: "exam_question_submit" %>
    </div>
  <% end -%>
</div>

<script type="text/javascript">
//<![CDATA[

  $('#edit_exam_question_<%= @exam_question.id %> :checkbox').change(function(){
    $('#newexamloader').show();
    $("#edit_exam_question_<%= @exam_question.id %>").submit();
  })

//]]>
</script>

app/views/exams/index.html.erb
<h2>Exams (<%= @num_of_exams %>)</h2>

<p>
  generated: <%= @generated_count %>,
  started: <%= @started_count %>,
  checked: <%= @checked_count %>,
  completed: <%= @completed_count %>
</p>

<%= will_paginate @exams %>

<table class="listing">
  <tr>
    <th>id</th>
    <th>state</th>
    <th>sessionid</th>
    <th>created at</th>
    <th></th>
  </tr>

<% for exam in @exams %>
  <tr class="<%= cycle('odd', 'even') %>">
    <td><%= exam.id %></td>
    <td><%= exam.state %></td>
    <td><%= exam.sessionid %></td>
    <td><%= exam.created_at.to_s(:db) %></td>
    <td>
      <div><%= link_to 'Show', exam %></div>
      <div><%= link_to 'Destroy', exam, :confirm => 'Are you sure?', :method => :delete %></div>
    </td>
  </tr>
<% end %>
</table>

app/views/exams/new.html.erb
<% if @exam.errors.any? %>
  <div id="errorExplanation">
    <h2>Invalid data. Can't generate a new exam.</h2>
    <ul>
    <% @exam.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div id="info" class="rbox">
  <h2>Do you really know Ruby?</h2>
  <p>
    REXAMINATOR is another one online exam simulator that can help you test and improve your knowledge of
    <strong>Ruby</strong> programming language.
  </p>
  <p>
    Right now, you can test yourself online with multiple choice test simulator - no user registration required - just go and enjoy:)
  </p>
  <p>
    <strong>NOTE:</strong> This is a test version with only tens of sample questions on board.
  </p>
</div>

<div id="start" class="rbox">
  <h2>&raquo; START HERE &laquo;</h2>
  <%= form_for @exam do %>
    <div>
      <%= label_tag :num_of_questions, 'Number of Questions ' %>
      <%= text_field_tag :num_of_questions, nil, :size => 3, :maxlength => 3, :title => 'Number of questions for new exam (1-30)' %>
    </div>
    <div id="newexambutton">
      <%= submit_tag "Generate New Exam", :title => "Click to generate new exam", :class => "rbutton" %>
    </div>
  <% end %>
</div>

<div id="newexamloader"></div>

app/views/exams/show.html.erb
<h3>Exam Id:</h3>
<p>
  <%= @exam.id %>
</p>

<h3>State: </h3>
<p>
  <%= @exam.state %>
</p>

<h3>Session ID:</h3>
<p>
  <%= @exam.sessionid %>
</p>

<h3>Questions:</h3>
<ol class="showing">
<% for question in @exam.questions %>
  <li>[<%= question.id %>] <%=h question.body %></li>
  <ol type="a" class="showing">
    <% for answer in question.answers %>
      <li>[<%= answer.id %>] [<%=to_sign answer.correct %>] <%= answer.body %></li>
    <% end %>
  </ol>

<% end %>
</ol>
<%= link_to 'Back', exams_path %>

app/views/exams/start.html.erb
<div class="center">
  <h2>New exam has been successfully generated.</h2>
  <p>Number of questions: <strong><%= @num_of_questions %></strong></p>
  <ul id="startmenu">
    <li><%= link_to "Start Exam", go_exam_url(@exam), :class => "rbutton", :title => "Examine your Ruby knowledge online" %></li>
  </ul>
</div>